version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ..
      dockerfile: /docker/Dockerfile
    container_name: next-app
    environment:
      DATABASE_URL: postgres://user:password@database:5432/postgres
      LOCAL_URL: http://host.docker.internal
    depends_on:
      - database
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data: